# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 754c5479d95645f128658a199e7ef5819d31456137bee0774d2f2a427c6983fd3b25a3d38210f9a87bf47da64a6bf7cf66bdf3781cee7cb23f799ba3e9807f45

test:
  secret_key_base: 8e8426ac875a0e6493d993388d4be8adb3f04ddcd3e9f5989c2d424073896ec00201f47a529fe394ec6c4c539c890310a5c2f8a08c51f28dc8421c87927a9a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
